---
applications:
- name: SupplyChainNetworkFlowPath-UI
  memory: 512M
  instances: 1
  command: npm start
  buildpack: https://github.com/cloudfoundry/nodejs-buildpack
  routes:
  - route: supplychainnetworkflowpath-ui.apps-zb.homedepot.com
  - route: supplychainnetworkflowpath-ui.apps.homedepot.com
  services:
    - supplychainnetworkflowpath-sso
  env:
   config: '{
        "SSO_URL": "https://sso.login.run-zb.homedepot.com",
        "SSO_CLIENT_ID": "",
        "FLOW_PATH_URL":"https://supplychainnetworkflowpath.apps-zb.homedepot.com/directFulfillment/vendorSKUNetwork"
    }'